modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
# issueTrackerURL="" #optional
[[mods]] #mandatory
modId="peoplemobsmod2" #mandatory
version="${file.jarVersion}" #mandatory
displayName="People Mobs Mod2" #mandatory
# updateJSONURL="" #optional
# displayURL="https://twitter.com/super_amateur_c/" #optional
# logoFile="modlogo.png" #optional
# credits="" #optional
authors="どどど素人(super_amateur_c)" #optional
description='''

    世界は僕と
        女の子でできている。
'''

[[dependencies.peoplemobsmod2]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.peoplemobsmod2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
